name: bench_breast_cancer_linear_toy
logger:
  level: INFO
  path: ./logs/benchmark_batch_2x2x5/bench_breast_cancer_linear_toy.log
caching:
  path: ./cache/benchmark_batch_2x2x5/
dataset:
  name: breast_cancer
preprocess:
- name: scale
  seed: 42
  scaling: standardize
  range: true
- name: split
  seed: 42
  split: 0.2
  sample: 30
model:
  name: linear
  seed: 42
  device: cpu
  epochs: 80
  learning_rate: 0.01
  batch_size: 32
  optimizer: adam
  criterion: cross_entropy
  output_activation: softmax
method:
  name: toy
  seed: 42
  device: cpu
  desired_class: 1
  max_iterations: 200
  step_size: 0.05
  lambda_: 0.05
  clamp: true
evaluation:
- name: validity
- name: distance
  metrics:
  - l0
  - l1
  - l2
  - linf
- name: ynn
  k: 5
- name: runtime

